# Generated by Django 5.0.2 on 2024-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposcar', '0006_alter_bet_category_alter_bet_movie_alter_bet_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nominees',
            field=models.ManyToManyField(blank=True, null=True, related_name='nominations', to='aposcar.movie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Main', 'Main'), ('Sup', 'Sup'), ('Tech', 'Tech')], default='Main', max_length=4),
        ),
    ]
