# Generated by Django 5.0.2 on 2024-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposcar', '0008_alter_category_nominees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nominees',
            field=models.ManyToManyField(blank=True, null=True, related_name='nominations', to='aposcar.movie'),
        ),
    ]
