# Generated by Django 5.0.2 on 2024-02-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposcar', '0009_alter_category_nominees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='aposcar.category'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='aposcar.movie'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='aposcar.receiver'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nominees',
            field=models.ManyToManyField(blank=True, related_name='nominations', to='aposcar.movie'),
        ),
    ]
