# Generated by Django 5.0 on 2024-02-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aposcar', '0010_alter_bet_category_alter_bet_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='letterboxd',
            field=models.URLField(blank=True, null=True),
        ),
    ]
